package com.mymedicalhub.emmavirtualtherapist.android.feature_bot.domain.model

data class ResponseData(
    val audioUrl: String,
    val bodyLocation: String,
    val bodyParts: List<BodyPart>,
    val botName: String,
    val buttonText: String,
    val chatEnded: Boolean,
    val dialogue: String,
    val disableBodyPartIds: List<String>,
    val editable: Boolean,
    val exercise: Any?,
    val header1: String,
    val header2: String,
    val hint: String,
    val id: Int,
    val intent: String,
    val lastQuestionInGroup: Boolean,
    val pageCaption: String,
    val questionId: Int,
    val responseType: ResponseType,
    val responses: List<Response>,
    val saveAnswer: Boolean,
    val selectedBodyRegions: List<String>,
    val sessionId: String,
    val skipped: Boolean,
    val tenant: String,
    val text: String,
    val title: String,
    val typeId: Int,
    val typeName: String,
    val vasQuestion: Boolean,
    var answers: List<Response> = emptyList()
)